# Generated by Django 3.1.7 on 2021-03-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100, verbose_name='Имя')),
                ('user_email', models.EmailField(max_length=200, verbose_name='Электронная почта')),
                ('user_text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('active', 'Активная'), ('blocked', 'Заблокировано')], default='active')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': 'GuestBook',
            },
        ),
    ]
