# Generated by Django 3.1.7 on 2021-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='user_email',
            field=models.EmailField(max_length=200, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='user_text',
            field=models.TextField(max_length=2000, verbose_name='User Text'),
        ),
    ]
